### ISSUE TITLE
Separate unit test suite for automated Mimi model testing

### ISSUE THREAD

**Issue by jrising** [anthofflab/Mimi.jl#112]
Currently, the entire suite of unit tests is run for each model when Mimi is tested (through `runtests.jl`).  In my case, some tests have nothing to do with the Mimi framework.

I propose that the model testing code first check for a `mimitests.jl` script, and only fall-back to run `runtests.jl` if it is not available.

**Comment by davidanthoff** [comment]
@ckingdon95 Would be great if you could look at that, maybe even in this iteration?

**Comment by ckingdon95** [comment]
will do!

**Comment by ckingdon95** [comment]
just curious though, what kind of tests would someone do on their model that doesn't have to do with Mimi framework?

**Comment by jrising** [comment]
I have tests of my data caching system, my network merge functions, and my reservoir processing functions.  I love your question though.  "Why would anyone want to test anything other than their full Mimi model?"

**Comment by ckingdon95** [comment]
PR #118
