### ISSUE TITLE
`checklabels` uses `parametername` rather than `name`

### ISSUE THREAD

**Issue by jrising** [anthofflab/Mimi.jl#129]
If you use `connectparameter(m::Model, component::Symbol, name::Symbol, parametername::Symbol)` to connect a components parameter named `name` to an external parameter named `parametername`, it will fail if `parametername` is not the same as `name`, because assumes that the component's parameter is named `parametername` rather than `name`.

In fact, `checklabels` takes in both `name` and `parametername`, but does not reference `name` at all.

**Comment by davidanthoff** [comment]
I believe this was fixed, at least on ``master``? I'll close this for now, please reopen if that is wrong.

**Comment by ckingdon95** [comment]
yep it was merged!

**Comment by jrising** [comment]
Thanks!

 - James
