### ISSUE TITLE
Order of unit tests init to not be run in Mimi-Page

### ISSUE THREAD

**Issue by jrising** [anthofflab/Mimi.jl#131]
I just wanted to put this here, but I don't have a good description of the problem, except to say what happened in Mimi-Page.  When the ClimateTemperature component is run after some other unit tests, its `init` function is never called.  See https://github.com/anthofflab/mimi-page.jl/pull/108

**Comment by davidanthoff** [comment]
Should be solved, just reconfirm.

**Comment by jrising** [comment]
Confirmed.  At least, when I put the order back the way it was, the error no longer reproduces.
