### ISSUE TITLE
Tracking: Ready for outside collaboration through GitHub

### ISSUE THREAD

**Issue by NHDaly** [anthofflab/Mimi.jl#150]
Following-up from an in-person chat with @davidanthoff at JuliaCon, this is a tracking-issue to track when this repo and [davidanthoff/FUND.jl](http://github.com/davidanthoff/FUND.jl) are ready for contributions from outside the lab.

Things we discussed that would make that easier:
 - Creating Issues to track ongoing work internal to the lab
 - Labelling your Issues with outside-friendly labels (e.g. `Documentation-needed`, `beginner-friendly`, some sort of time estimate, etc.)
 - A contributions guide page

Please do update this bug when you are ready to accept external contributions! :)

**Comment by davidanthoff** [comment]
@NHDaly so I think the place where we are is this: we are more than happy to accept PRs that improve things. We also have a pretty solid internal team that is working on larger new features, designs etc. So we'll close this issue, and would welcome any PRs :)

**Comment by NHDaly** [comment]
Sorry it's been almost a year since you posted this! Thanks for following up with this eventually; I'm happy to hear things are in such a great state! :)

Also, it was a pleasure to see you all last summer, and looking forward to hopefully seeing you again this summer in Lisbon! 😁 
Unfortunately I'm quite busy with work at RelationalAI now, and probably won't have much time to go Issue hunting, but if something comes up you can always find me. :)

Also, I don't know if you've seen, there's a `#climate` channel on the Slack now, which might be a good place to solicit contributions if that is something you are actively seeking out!:
https://julialang.slack.com/archives/CNK8SLW58

**Comment by davidanthoff** [comment]
Yes, hopefully we'll all see each other in Lisbon!
