### ISSUE TITLE
More specific warning for setparameter errors

### ISSUE THREAD

**Issue by FrankErrickson** [anthofflab/Mimi.jl#151]
I've been modifying some Mimi models so that the dimensions of various parameters change from the base version of the model.  For instance, a savings rate parameter indexed by time would now be indexed by time and region.  This process involves lots of parameters, and inevitably I miss a couple during the setparameter( ) stage of creating the model by passing in a vector rather than a 2-d array.  

Now the problem comes from the error message I receive, which is "TypeError: setfield!: expected Array{Float64,2}, got Float64".  There's no other useful information, requiring me to go through every single parameter to cross-check that I have the correct dimensions.  If it just gave me the name of the parameter or even the component that caused the error, it would save a lot of time and make it much easier to find the bug.

**Comment by lrennels** [comment]
@FrankErrickson have you had any troubles with this type of error lately?  I believe we've now implemented lots of `ERROR` messages to catch these problems, but before I close the issue I wanted to check with you!
