### ISSUE TITLE
Throw an error when setting a parameter that doesn't exist. 

### ISSUE THREAD

**Issue by FrankErrickson** [anthofflab/Mimi.jl#156]
I accidentally misspelled the name of a parameter when using `setparameter`, but Mimi did not throw an error.  I can actually set lots of values for parameters that don't exist in my model, and it does not throw an error until I try to actually run the model.   Maybe there's a way around this, but I ended up reconstructing my model.  If the error just occurred one step earlier (when I try to set a non-existent parameter) that would make life easier.

Just as an example, this code will run:

`setparameter(rice_air, :welfare, :FAKE_PARAMETER!!!!!, 0.0)`

**Comment by rjplevin** [comment]
This now produces the error: `ERROR: Parameter foo was not found in component grosseconomy`
