### ISSUE TITLE
Simplify Component Structure

### ISSUE THREAD

**Issue by FrankErrickson** [anthofflab/Mimi.jl#157]
These comments are based on trying to get the Princeton group up and running with Mimi...

First, it's not clear to me why the `@defcomp` and `run_timestep` have to be separate.  If they can just be combined into one single component creation block of code, that would be more intuitive for new users.

Second, having to declare the `state` and `t::Int` as well as all of the variable/parameter declarations (i.e. I have some code using ` v, p, d = getvpd(state)` and other code that uses the  `v = state.Variables` syntax...not sure if any of this is now outdated) was the main source of confusion.  If this can all be folded into the background it would make it much easier for new users.  My suggestions:

(1) The `v.` and `p.` syntax always identifies variables and parameters and that's just how the syntax works.  I've never had a case of needing a different specification.  The user does not have to define this.

(2) Have one part where the component is given a name, and automatically tie that to the `state` setting in the component.

(3) Always have time indexed by `t` and specified as an integer.  If people are using non-integer (or some other unusual) time indices, they are probably pretty familiar with Mimi/coding in general and can have some special command for a unique timestep.

(4)  Just have clear instructions for adding extra dimensions that specifies the name and syntax symbol in a user friendly (preferably a single line) command.  Something like:
```
#Define a new region index
regions = Index(r)
```
The regions would be the name of this new index.  The `r` would be used to specify this index in model equations (i.e. an equation would still be v.result[t,r] = p.parameter[t,r] + 4)

**Comment by davidanthoff** [comment]
So we are leaning to the following syntax right now, I'd be interested to hear your feedback.
````julia
@defcomp foo begin
  a = Variable()
  b = Parameter()

  function run_timestep(v,p,d,t)
    v.a = 2 * p.b
  end
end
````
So users still have to pick names for ``v``, ``p`` etc., but they are now just normal function arguments. We could just hard-code those, but in some sense it seemed clearer to use to use normal function syntax here and don't be too magical?

I'll have to think a bit about the region index idea... Or even better, @FrankErrickson could you open a separate issue for that? It seems a quite distinct question.

**Comment by FrankErrickson** [comment]
@davidanthoff I think this is much clearer than the current syntax and just using normal function syntax would probably make it more familiar to people that don't code a ton.  I don't know much about the internals of Mimi, but I still wonder (if it's possible) if getting rid of the run_timestep function and hardcoding things would make it more user friendly.  I think it's just not terribly intuitive for people what a run_timestep is.  Here's a quick example just to give an idea of what I'm thinking.

```julia
    @defcomp foo begin
        country = Index()
        a = Variable()
        b = Parameter()

        #Start equations here with no special arguments required.
        for c in d.country
            v.a[t,c] = 2.0 * p.b[t,c]
        end
    end
```

So in this stripped down version, `p` and `v` are hardcoded to indicate parameters and  variables.  `t` is hardcoded for the time index, and `d` is hardcoded to automatically indicate a dimension (though you could probably get rid of the `d` and just not allow users to have something else with the same name as one of the indices).  The user doesn't have to specify any type of function, perhaps Mimi could just internally build the timestep function by looking for the first line with an `=` not followed by the Index, Variable, or Parameter commands (I'm assuming there's a smart software development way to do this).  I'll open a separate issue for the index thing.

**Comment by rjplevin** [comment]
In the dot-overloading branch (soon to be merged with master), we now have the syntax @davidanthoff described for run_timestep (actually called `run` in the implemented version, plus the option of defining an `init(p, v, d)` function that's called for each comp before iterating over timesteps.

Stripping out the `function run(p, v, d, t)` declaration won't work since there are now two separate sets of code it identify. I think with examples to work from, this won't be too confusing. I'm closing this issue for now. If the new version doesn't satisfy, open a new issue and we'll discuss!
