### ISSUE TITLE
Simplify adding new dimensions/indices.

### ISSUE THREAD

**Issue by FrankErrickson** [anthofflab/Mimi.jl#171]
It would make things more user friendly if the current set up for adding a new dimension/index was simplified.  It seems like some of this might get addressed with how the whole `@defcomp` command is being updated (i.e. not having to write out d = s.Dimensions).  But it'd be great to have something where you specify the name of the new dimension (preferably a single line command) and don't have to write anything else for it to work.   Here's an example that also uses the syntax you are thinking about to simplify the timestep function,
```julia
    @defcomp foo begin
        country = Index()
        a = Variable()
        b = Parameter()

        function run_timestep(v,p,t)
            for c in country
                v.a[t,c] = 2.0 * p.b[t,c]
            end
        end
    end
```
In this case the user just supplies a name for their new index.  If they want to loop through it in an equation, they would just set it up like any standard for loop.  I removed the `d` declaration here just to simplify things more.  In this case, the user just couldn't have any local variables named `country`.

**Comment by davidanthoff** [comment]
Take a look at the new version once it is out, I think it makes things easier for this case.
