### ISSUE TITLE
Integrate Timestep into a type hierarchy starting with AbstractIndex

### ISSUE THREAD

**Issue by rjplevin** [anthofflab/Mimi.jl#173]
Merge new Index type with TimestepVector/Matrix classes. Initial thoughts:

* AbstractIndex
  * AbstractTimestep
    * UniformTimestep
    * NonUniformTimestep
  * SymbolicIndex (Symbols or Strings)
  * AbstractNumericIndex (integers that don't represent time)
    * UniformNumericIndex (e.g., created with a Range)
    * NonUniformNumericIndex

**Comment by davidanthoff** [comment]
So one thing that I really like about this is that we can probably start with parts of that and then later extend. For example, if for now we started just with the stuff below ``AbstractTimestep``, we might be able to get things working nicely for PAGE relatively soon. And then later we can add the other types.
