### ISSUE TITLE
Use custom types rather than ad hoc combinations of base types

### ISSUE THREAD

**Issue by rjplevin** [anthofflab/Mimi.jl#175]
It is often beneficial to hide (some) implementation details behind types. For example, when two Symbols are carried around together, (e.g., to identify module and component, or component and variable) we can instead use simple 2-element structs:

```julia
type ComponentKey
    module::Symbol
    name::Symbol
end

type DatumKey
    comp_key::ComponentKey
    name::Symbol
end
```

An advantage of this approach is that one need only specify a single type for elements that “travel” together. Another is that the struct can become more complex if required with minimal changes to much of the API.

**Comment by davidanthoff** [comment]
Definitely! Probably best to make these ``struct``s.
