### ISSUE TITLE
Eliminate (nearly) redundant types

### ISSUE THREAD

**Issue by rjplevin** [anthofflab/Mimi.jl#176]
Consider eliminating type `ExternalParameterConnection`. This can be represented by an `InternalParameterConnection` with component name `nothing`. The main difference appears to be that external parameter connections are stored in a separate list in `Model`. Rename the remaining type simply `ParameterConnection`. 

It would be useful to maintain these separate types if we were dispatching on them, but I found no function dispatch on these types, so combining these types would be simpler.

**Comment by davidanthoff** [comment]
Maybe make the component name a ``Union{Symbol,Void}``? Then folks can still name their component ``nothing`` if they want.

@ckingdon95 does this make sense to you? Just wondering whether we are overlooking some twist here.

**Comment by ckingdon95** [comment]
Sounds good to me! So then would a `ParameterConnection` have fields:

`target_component::Symbol`
`target_parameter::Symbol`
`source_component::Union{Symbol,Void}`
`source_value_name::Symbol`

Not sure what the last one should be called; it's a either an external parameter or a variable in another component, depending on if it's an external or internal connection

**Comment by rjplevin** [comment]
How about "datum" as the unifying name for either Parameter or Variable? So the final element would be `source_datum_name`.

**Comment by ckingdon95** [comment]
perfect!
