### ISSUE TITLE
Review type hierarchy for model data and connectors

### ISSUE THREAD

**Issue by rjplevin** [anthofflab/Mimi.jl#178]
Consider how to unify or simplify vector/matrix subtype such as `TimestepVector` and `TimestepMatrix`, `ConnectorCompVector` and `ConnectorCompMatrix`. 

David mentioned that we in particular need to think hard how this can be extended to strongly typed indices for dimensions other than time. See also #145 and #173.

**Comment by davidanthoff** [comment]
So I think we should tackle this at the same time when we get to designing something that allows us to couple components that run on different say regional grids, and then try to unify and simplify that with the whole time story, somehow...
