### ISSUE TITLE
Decompose large files

### ISSUE THREAD

**Issue by rjplevin** [anthofflab/Mimi.jl#179]
The file mimi-core.jl is currently 1,369 lines long, which is unwieldy and should be refactored into a few separate files.

Object-oriented languages provide a natural structuring of files since methods “belong” to one class or another. With multiple-dispatch, it is less clear how to sort methods into files. However, I think we should define separate files for the major struct types in Mimi: component, model, parameter / variable (related closely enough to manage together), and connections.

We might use a “containment” criterion for sorting methods into classes. In Mimi, models contain components and connections; components contain variables and parameters, and connections link parameters and variables. If a method takes multiple types from this hierarchy, it should live in the file with the outermost container. So, `foo(m::Model, …)` would appear in model.jl, and `foo(c::Component, … anything but Model …)` would appear in component.jl, and so on.  

A challenge with this approach is the preponderance of methods that take a Model parameter. We might further divide these into “primary” and “secondary” model methods, recognizing that this is somewhat subjective. For example, the suite of `getdataframe()` methods (about 130 lines of code) could be considered secondary as they do not constitute the core of Mimi, but are provided as a convenience for accessing results. Methods focused on parameters and variables might also be migrated to a distinct file, e.g., model_data.jl.

Suggested refactoring of mimi-core.jl:

- model.jl -- Model and ModelInstance (or ModelDef) types and methods
- component.jl -- Component, ComponentInfo types and methods
- model_data.jl -- Parameter and Variable types and methods
- defcomp.jl -- @defcomp macro and helper functions it requires
- model_utils.jl -- Ancillary methods for accessing model and model data.

David commented that a pattern that a lot of julia packages use is to have one file that holds all the types, but no methods. The benefit is that you can include the types first, and then be sure that all types are already declared when you define methods.

**Comment by davidanthoff** [comment]
I've started this a little bit in #174: the idea would be to have everything related to ``ModelInstance`` in a sub folder. Then have one file that has all the types defined in it, and separate files for the various methods. I do think having all the types in one file might be good for two reasons: a) we don't have to worry that much about include ordering, and b) one can get a fairly quick sense how the various types interact. So maybe we'll try that kind of structure and see how it goes?

**Comment by rjplevin** [comment]
I'm willing to try the "all types in one file" approach. It's sort of like a *.h / *.c breakdown, which is  familiar enough. But I don't completely like it since methods defined inside the type are separated from those defined outside the type, impairing intelligibility and maintenance slightly.

I'm still not happy with the way Julia handles files and modules. Though confusing at first, the Python approach supports a more sensible internal file structure. Multiple dispatch makes it more of a challenge...

**Comment by davidanthoff** [comment]
Yeah, inner constructors will have to stay in the files for the types, no way around that.

**Comment by rjplevin** [comment]
Refactoring largely done in dot-overloading branch.
