### ISSUE TITLE
Break add_components() into sub-functions

### ISSUE THREAD

**Issue by rjplevin** [anthofflab/Mimi.jl#181]
The method `add_components()` can be simplified by relying on a data structure that supports insertion into an ordered sequence. (Rich has written a MutableOrderedDict that needs to be merged into the code. However, this may be obviated by automatic order detection using a DAG.)

**Comment by rjplevin** [comment]
Added initial support for automatic ordering of components by creating a directed acyclic graph using LightGraphs.jl. Still need to:

- test it on a non-trivial model
- accommodate references that would be cycles if not referring to prior timestep

**Comment by davidanthoff** [comment]
I think the automatic ordering is not going to be easy. I think every non-trivial model we have will have cycles that are only broken via prior timestep references, so we would need to add a full semantic understanding for that. That would be cool, but I think we should put this on the backlog and first implement the things we need to implement :) This also hasn't really been much of an issue in practice, so I'd say lets not spend resources on that at this point.
