### ISSUE TITLE
Break build() into sub-functions

### ISSUE THREAD

**Issue by rjplevin** [anthofflab/Mimi.jl#182]
The method `build(m::Model)` is currently 111 lines long, which is difficult to test or debug. It contains some ad hoc code generation that might be better written as a macro. It’s generally not a good thing when you find yourself writing:

```julia
    comp = eval(eval(constructor))
```

**Comment by davidanthoff** [comment]
So this is where I got stock in my efforts... It is a beast, and breaking it up is the only chance we have. The double ``eval`` can go away with the dot overloading story.

**Comment by rjplevin** [comment]
Done in dot-overloading branch.
