### ISSUE TITLE
Use iterable tables interface for loading

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/Mimi.jl#209]
Dependencies we need: TableTraits.jl, IterableTables.jl.

http://www.david-anthoff.com/jl4ds/latest/tabletraits.html

**Comment by rjplevin** [comment]
This doesn't suffice for loading a specific range from an Excel worksheet, e.g., "Sheet1!A10:B45"...

**Comment by davidanthoff** [comment]
``load("filename.xlsx", "Sheet1!A10:B45")`` should just work?

**Comment by rjplevin** [comment]
Where are the optional args to `load` documented?

**Comment by davidanthoff** [comment]
http://www.david-anthoff.com/jl4ds/latest/fileio.html#Excel-Files-1 and https://github.com/davidanthoff/ExcelFiles.jl.
