### ISSUE TITLE
Error: "Mismatch datatype of parameter connection"

### ISSUE THREAD

**Issue by FrankErrickson** [anthofflab/Mimi.jl#224]
I cannot run the default Mimi version of SNEaSY (the one hosted on AnthoffLab).  I get an error saying, 

`Mismatched datatype of parameter connection. Component: ccm, Parameter: anomtable`.

The `anomtable` parameter is an array of numbers that remains unchanged over time.  It is declared in the ccm component as `anomtable::Array{Float64,2} = Parameter( )`.  This code used to run, but hasn't worked for a few months now.  Are there any plans to fix this in the Mimi updates, and any idea on when a stable version of Mimi that fixes this will be released?  I have to read in anomtable as external data and force it into the carbon cycle component, which isn't ideal or fast for MCMC.

**Comment by lrennels** [comment]
@FrankErrickson I can take a look at this for you.  It's also on my list to create a version of SNeaSY that will run with the new version of Mimi, which includes a few minor API changes.  That'll be on a branch called `integration`, which we can then merge into master when we release the new Mimi.  In the meantime it seems like we should be able to find a fix.  @rjplevin @davidanthoff I'll let you know if I need help sorting through this.

**Comment by lrennels** [comment]
@rjplevin this error is coming out of `mimi-core.jl` at line 237:

**Comment by rjplevin** [comment]
I'm not familiar enough with the old architecture to anticipate the repercussions of any quick fix. I can take a look at it tomorrow, though...

**Comment by FrankErrickson** [comment]
@lrennels Thanks for looking into this.  I ended up just creating some fake model indices with the proper dimensions so I could read in `anomtable` as a Mimi parameter.  It's clumsy, but that was a lot faster than reading it in as external data.  If I have a chance to try your suggestion and compare the results, I will let you know which works out better.

So there's no rush to fix this (in terms of running SNEaSY), but in general it would be nice to have flexibility in the types of parameters you can read in for the next super-duper version of Mimi.
