### ISSUE TITLE
Fix lowercase external parameter bug

### ISSUE THREAD

**Issue by lrennels** [anthofflab/Mimi.jl#246]
Currently Mimi's `set_leftover_parameters` function enforces that external parameters set in the function file are lowercase.  This bug will be removed.  

@jrising this will allow you to remove lowercase conversions from PAGE's Montecarlo support functions, which I have now done in my branch as I convert `PAGE` to our new Mimi framework, but wanted to loop you in on this change.

**Comment by jrising** [comment]
This will be appreciated!  Thanks.
