### ISSUE TITLE
Conceptual question about Timesteps

### ISSUE THREAD

**Issue by rjplevin** [anthofflab/Mimi.jl#247]
I spent a couple of hours debugging test_timesteps.jl today. I found a conceptual error that could be resolved various ways. I'm looking for input from the experienced Mimi modelers.

Note that we decided to eliminate passing time to `run_timestep` as an integer index, instead passing either a `FixedTimestep` or `VariableTimestep`. So this problem may disappear in that transition.

The function `addcomponent` has an optional argument `first` that indicates the first time (a year, for now) that this component should run. A component with an "offset" like this can be connected to a component with a different offset, or no offset. This scrambles the interpretation of `t` in `run_timestep`, since the same index implies different years in the 2 components. This allows "shorter" components to allocate less storage than they would otherwise have to.

This should be resolved when moving exclusively to `ts::AbstractTimestep` in `run_timestep` functions, since we're explicit about year and implicit about array position, rather than the other way around.

It's not clear to me whether this "offset" feature is actually used, and if so, how this was working in version 0.4.0. I'd like to be sure the new version doesn't violate any assumptions in existing models.

**Comment by davidanthoff** [comment]
I think our idea had been that this whole feature would only work if one uses ``Timestep`` indices, not with just ``Int`` indices. I don't think it is being used anywhere right now. I think the best way forward on that is to just ditch the whole ``Int`` timestep variant, and require folks to use the proper timestep types.

**Comment by lrennels** [comment]
This makes sense to me, we currently do have portions of the code in Mimi that are meant to support this old way of indexing.  I could remove these before the release if that is desirable.

**Comment by lrennels** [comment]
Notes for removing `Int` tilmestep variant:

- remove `ci.use_integer_time` flag

```
mutable struct ComponentInstance{TV <: ComponentInstanceVariables, TP <: ComponentInstanceParameters}
    ...
    use_integer_time::Bool                  # will be deprecated when switching to timesteps in all cases
```

- remove methods in `time.jl` with comment # int indexing version supports old style components

**Comment by rjplevin** [comment]
For clarity, the change should be to this, with the `where` bit after the parenthesized arguments. (Inside doesn't create the correct code...)

```
    func = :(
        function $(funcname)($(p)::Mimi.ComponentInstanceParameters, $(v)::Mimi.ComponentInstanceVariables, 
                             $(d)::Dict{Symbol, Vector{Int}}, $(t)::T) where {T <: Mimi.AbstractTimestep}
            $(body...)
            
            return nothing
        end
    )
```

**Comment by lrennels** [comment]
Great I was about to experiment with that!

**Comment by lrennels** [comment]
Per the simplification of `types.jl`, you mean we can get rid of this whole block:

```
if func != nothing
            meths = methods(func)
            meth = meths.ms[1]
            arg_types = meth.sig.parameters

            # This is used to determine type of time argument to pass to run_timestep
            time_type = arg_types[length(arg_types)]

            # if time_type <: AbstractTimestep
            #     self.use_integer_time = false
            # end       
        end  
```

**Comment by lrennels** [comment]
Still TODO: (for Lisa)
- update tests and make sure to thoroughly test functionality
- decide how to handle `x + ts`, `x * ts`, etc. in models 
- update examples
- update docs (check general, internal, and porting doc)
- fix all integration branches

**Comment by rjplevin** [comment]
Right. The only outcome of that block is setting `use_integer_time`, so we can delete it.

**Comment by lrennels** [comment]
Cases of using t.t:
