### ISSUE TITLE
Improve docs on `init()`

### ISSUE THREAD

**Issue by lrennels** [anthofflab/Mimi.jl#257]
PR #264 

We need to firm up the semantics of init() vs run_timestep().

Is init called before any timesteps, or is it called on the first timestep?
If init is called on the first timestep, should run_timestep run only from the 2nd timestep forward?
What if a component is run with an offset (i.e., it starts after the first global timestep)?

Currently, init() is called for all components before the timestep loop, which at least is easy to explain, but then run_timestep() needs to avoid redundant behavior in 1st real timestep. Perhaps we should start by enumerating the use cases?

**Comment by davidanthoff** [comment]
I think we should leave ``init`` to just run before anything else. The idea would be that one can used it to e.g. compute the values of scalar variables that only depend on scalar parameters. One would not use it, though, to compute anything that has a time index.

``run_timestep`` would still be run for every timestep, as it is right now. One might still need special handling for the first timestep, in particular for difference equations, but I think that is ok.
