### ISSUE TITLE
Add API to get the index information for parameters and variables

### ISSUE THREAD

**Issue by jrising** [anthofflab/Mimi.jl#27]
Currently, the dimensions of a variable are available from `meta[(:Main, component)].variables[name].dimensions`, and for a parameter from `size(model.parameters[name].values)`.  There should be documented functions like `variableindices` and `parameterindices`, which would return the index names to then be passed to new `indexcount` and `indexvalues` functions.

**Comment by jrising** [comment]
This no longer works, after version 0.2.0, since models no longer have a parameter attribute.

**Comment by davidanthoff** [comment]
Both for this and for #26, do you need an API that works from within ``run_timestep`` (in which case you don't have access to the model instance), or from outside, i.e. with a ``Model`` instance in hand?

I guess in the end we should enable both, so this is more a question about priorities than anything else.

**Comment by jrising** [comment]
Currently, my biggest need is in OptiMimi and not within `run_timestep`: for all of these uses, I will have a `Model` instance.

**Comment by ckingdon95** [comment]
PR #86
