### ISSUE TITLE
Default parameter Integer assumption

### ISSUE THREAD

**Issue by ckingdon95** [anthofflab/Mimi.jl#286]
Currently if a user sets the default parameter value to an Integer, there will be an error later if a monte carlo simulation attempts to assign a float value to that parameter. Is this the functionality that we want? Or should we type these parameters as Floats?

**Comment by rjplevin** [comment]
I think if it's a parameter than can be a float, the default should be a float as well. 

In theory, the parameter declaration can specify the type, so this would result in a float value, even though the default is an Int:
```
share::Float64 = Parameter(default=1)   
```
However, I tested this and it's not working. I will debug... In the meantime, this should work:
```
share = Parameter(default=1.0)   
```

**Comment by ckingdon95** [comment]
Okay I will add the decimal places, I think that makes the most sense!
