### ISSUE TITLE
Make replace_comp! re-connect parameters

### ISSUE THREAD

**Issue by ckingdon95** [anthofflab/Mimi.jl#289]
Do we want the replace_comp! function to re-connect any previously existing parameter connections to and from the component that's replaced?

**Comment by rjplevin** [comment]
I'd say yes, though I'd make it an optional argument to allow this behavior to be suppressed.

**Comment by ckingdon95** [comment]
other note for when I get around to working on replace_comp: I think the new component should get added in the same position in the component list as the old one, without requiring that the user specify a before or after argument

**Comment by rjplevin** [comment]
> Do we want the replace_comp! function to re-connect

How about an optional argument `reconnect::Bool=true`?

**Comment by ckingdon95** [comment]
PR #307
