### ISSUE TITLE
Require time index before adding components?

### ISSUE THREAD

**Issue by ckingdon95** [anthofflab/Mimi.jl#304]
Currently calls to add_comp! assume that the model's time index has already been set. Do we want to assert that the model must have a time index before you can add components? If so, we should catch the error and add a better message. If not, we need to make modifications to add_comp! to handle setting the first's and last's differently.

**Comment by lrennels** [comment]
I'd probably say asserting that the model needs a time index before adding components is valid.  That allows us to perform the kinds of checks and arithmetic between the model time index and component first/last etc. that we might want to do.
