### ISSUE TITLE
Complications with resetting the time dimension 

### ISSUE THREAD

**Issue by ckingdon95** [anthofflab/Mimi.jl#306]
Being addressed with PR #320 

I'm currently working on a modified version of PAGE. I start by getting the original version of page, then start making modifications to it, which include resetting the time dimension, replacing certain components, and updating certain parameter values. 

**Problem with components:**

The components that already exist have a first and last value of 2009 and 2200(the original time index). The new time index is 2010 to 2300. When I update the time index, the first values of the components get updated to 2010, and the last values stay the same at 2200 (because of the new functionality I implemented with the reset_run_periods function). But, this doesn't allow the old components to run on the full new time index, because the CompDef's stored value of 'last' says that the component can't run past 2200.  I think this might warrant a change to how the component first and last values get set. I think it could go like this:

- CompDef's should only store first and last values if the user explicitly gave a first and last value during calls to add-comp!. Otherwise, we should save them as 'nothing'
- Then during the build function, ComponentInstance's would get their first and last values set to whatever the model's time index is at that point, or if the user had explicitly specified first and last values that get stored in the CompDef, then set them to those. 

I think this makes the most sense because Component Definitions are supposed to be a more loose framework, not necessarily tied to a specific start and end value (unless explicitly defined by the user), and they should easily adapt to updates to the Model's dimensions, and then the Component Instance's get tied down with whatever the Model's dimensions are when they get instantiated.

Alternatively, if we really need CompDef's to not have 'nothing' stored in the first and lasts, then I think we need to provide some sort of optional "force_comps" flag in calls to set_dimension! that force components onto the new model time dimension (instead of carefully checking if the new range is wider or narrower than the comp_defs run period like rest_run_periods! does now). 

**Problem with external parameters:**

External parameters that were already defined in the model remain as Variable TimestepArrays with time labels of the old model index. It seems to me that if a user update's the time index, there should be an option for resetting the TimestepArrays that hold external parameter data. This raises questions though of how we want Mimi to interpret changes to the time dimension. If the user had originally provided external data on the old time steps, we probably shouldn't automatically convert it to the new timesteps. But maybe we can provide an option for this. 

For my purposes with page, the external parameters I want to update also involve updating the actual values stored. I have a PR open right now to improve the update_external_param! function to allow updates not just to the values stored, but also to the TIMES of the TimestepArrays that the values are stored in.

**Comment by rjplevin** [comment]
I agree that this suggests some redesign is needed. I'll look at it later today...

**Comment by rjplevin** [comment]
Regarding _problems with components_:

If I understand the problem correctly, it's a matter of handling two competing use cases:

1. Some components may need to set `first` and/or `last` to limit when the component should run.
2. Some components are more flexible and can adopt the time horizon set for the model.

I like @ckingdon95's suggestions that CompDefs store `first` and/or `last` only when it is intended to be a constraint, i.e., when the component doesn't make sense outside these bounds. However I'm not sure that a `force::Bool` flag to `set_dimension!` is sufficient. Might there be models with some components that should can be forced and others that should not? 

What about defining variants of `set_dimension!` with
* `force::Bool` (i.e., force all components to new time dimension), and
* `force::Vector{CompId}` which forces time for only the given components?

Does this cover all reasonable cases?

**Comment by rjplevin** [comment]
Regarding _problems with external parameters_:

I don't think we should automatically adjust external data to a new time dimension. It would be fine to allow an external param to be redefined. I would keep the responsibility for redefining the data with the model builder, rather than attempting it in some generic way within the framework.

**Comment by ckingdon95** [comment]
Regarding components: Yes your description covers all cases I am imagining. I was originally thinking that the force flag option would only be necessary if we didn't implement the first suggestion. But now are we thinking that the force flag could be used to change the time horizon even for components that explicitly have a different first/last value?

Regarding external parameters: I agree we shouldn't automatically do anything. I think we should maybe export the update_external_param! function though to give users this functionality

**Comment by lrennels** [comment]
By my interpretation, it does seem like we don't need both options i.e. either we (1) set the first and last in the `CompDef` if it's explicitly stated and otherwise do the setting of those parameters upon `build` or (2) we use the `force` option on `set_dimension!`.  I think either strategy could cover all cases, though I'm still getting my head around the cases.

**Comment by rjplevin** [comment]
I was thinking that some components (e.g., legacy) might unnecessarily set the time bounds but a savvy modeler might realize it's safe to override this, thus the "force". I think this would be an exception. As a general rule, we should recommend not setting bounds unless necessary.  

I agree that we should start with (1) and delay implementing `force` until we're sure it's necessary.

**Comment by lrennels** [comment]
Got it yes, we can implement the solution for the non savvy  programmer first and then add if we want to.

**Comment by lrennels** [comment]
Agreed on non-automatic updates, especially since that also makes a tough situation when trying to check matching parameter sizes to the data.   I’ll think about that one a bit more, exporting update_extremal_parameters might be a good call.  Also hopefully the two types timesteps doesn’t complicate this update too much but we need to be careful With those

**Comment by ckingdon95** [comment]
yes both! just that page has variable timesteps

this PR #305  adds an optional argument `update_timesteps` to the `update_external_param!` that redefines the timestep arrays (either fixed or variable) of an external parameter

**Comment by lrennels** [comment]
Got it.  I see the argument to not do it automatically, but I’m also slightly concerned that too many optional arguments make it harder to use or add potential mistakes that are hard for a user to debug.   I guess the question there is how often does this happen, and if it potentially causes a hidden bug if forgotten can we have a good warning message.   These are more design type questions but worth considering.  Thanks for opening those PRs Cora!

**Comment by lrennels** [comment]
I guess a typical user isn’t currently even using the update_external_params! function since it isn’t even exported yet so maybe I’m being overly cautious

**Comment by ckingdon95** [comment]
I think it's good to be cautious of too many options, and we should keep thinking about potential hidden bugs if we want to add this. But I would actually advocate for this function to be exported. I think it will be important for my work going forward. We will be doing lots of modifications to models that involve changing parameter values, and I see that as a main provided functionality of Mimi

**Comment by lrennels** [comment]
Great, glad we're on the same page and yes I see that being quite valuable.  What's the main argument for now doing this automatically with `update_external_param!` and the internals as opposed to an optional argument?  I guess there are so many cases where this would be unnecessary that it would be silly to try to detect it.  Currently, what would happen if you updated the time dimension, say to something longer than the original one, so that the parameter now doesn't have enough values?

**Comment by ckingdon95** [comment]
I think I don't fully understand your first question, but I think `update_timesteps` should still be an optional argument, with the default set to false, but that the whole function `update_external_param!` should be exported just so that users know about it. 

In terms of making the time index longer: currently update_external_param! can only update the timesteps if the new values are the same size as the old values (I check for this case and throw an error). But I think this warrants further design discussion about supporting calls to update with longer data arrays. (for example, instead of checking the size against the old values, it should check the size against the new time index maybe)

**Comment by lrennels** [comment]
Got it this makes sense to me now, sorry to be slow on the update :)

**Comment by ckingdon95** [comment]
@davidanthoff This is the issue that potentially needs your input. I think Rich, Lisa, and I are in agreement of what we want to change:

- Don't set a comp_def's `first` and `last` fields during calls to `add_comp!`, unless the user explicitly gives these values
- Then, during the build function, component instances will have their `first` and `last` values set to either the values from the comp_defs if they have them, or to the model's time index at that point
- This allows more flexible changing of a model's time index, so that if components were added before the time index is changed, they will automatically transition to the new time index, unless the user had explicitly set bounds on the component's run period

This all became relevant when trying to implement the IWG's version of PAGE, and also has implications on updating parameter values, which we are working on in a different PR ( #305 ).

@rjplevin @lrennels I'm not sure what complications we'll run into when trying to change this, but I am happy to try to work on this, unless we think it's better for someone else to tackle.

**Comment by davidanthoff** [comment]
Yes, I agree with your plan here!
