### ISSUE TITLE
restrict the visualization to a given time period with explorer?

### ISSUE THREAD

**Issue by hbenveniste** [anthofflab/Mimi.jl#390]
It would be great to be able to chose a specific time period when visualizing results for explorer. For instance focusing on 1950-2100 or 1950-2300, rather than all the way to year 3000.

**Comment by davidanthoff** [comment]
Maybe we could essentially do [this](https://discourse.julialang.org/t/interactive-plot-acting-as-a-range-slider-tool-for-another-plot/20392/4), and add an option to configure a default time range for a given model somehow?

**Comment by lrennels** [comment]
@davidanthoff good idea I'll look into this!

**Comment by davidanthoff** [comment]
First version: add keyword args to `explore`.
