### ISSUE TITLE
Tutorials Bugs

### ISSUE THREAD

**Issue by lrennels** [anthofflab/Mimi.jl#394]
Tutorial 1: Run an Existing Model

- [x] Under Step 2. Run FUND: M = getfund should read m = getfund()
- [x] Under Step 4. Access Results: Plots and Graphs: explore(m, “My Window”) should read explore(m; title=“My Window”)
- [x] I could not get the save(“MyFilePath.svg”, p) to work. I tried first using Plots and then save fig(p, “MyFilePath.svg”), but got an error indicating that this does not work for VegaLite plots. I was able to save a plot when I used p=plot(m[:socioeconomic, :income]), which created a plot using the GRBackend. Unfortunately, the x-axis did not show the years (see question below).

_try adding `VegaLite` and then type `using VegaLite`, I'll add this to the tutorial_

- [x] plot_comp_graph(m; filename = “MyFilePath.png”) should read plot_comp_graph(m, “MyFilePath.png”)

Comments on Tutorial 2: Modify an Existing Model
- [ ] I was unable to download the DICE model. I assume this is related to the model currently being in closed beta.

Comments on Tutorial 3: Create a Model

- [x] In regionparameters.jl: Need to update Array statements to read Array{Float64}(undef,20,3)
- [x] In running the model using my_model should read using .my_model

Comments on Tutorial 4: MCS Functionality
- [x] I am having problems with the run_mcs function. When I enter run_mcs(m, mcd, 4, output_dir=“/tmp/Mimi”), I get a Method Error indicating that I should not be entering the model name. In looking at the full signature of the function, though, I cannot figure out where to enter the model name.

_You need to flip the first 2 args to `run_mcs(mcs, m, 4, output_dir=output_dir`, also fixed in the tutorial_

**Comment by lrennels** [comment]
@daler6 what errors are you getting regarding Tutorial 1 save(“MyFilePath.svg”, p)`?

**Comment by lrennels** [comment]
@davidanthoff @ckingdon95  should both DICE2010 and DICE2013 still be private?  If so I need to move the tutorials away from using them, but it seems that with these repos becoming packages soon we could make them public?

**Comment by daler6** [comment]
@lrennels  I was getting the following error message when I used save("MyFilePath.svg", p)

ERROR: UndefVarError: save not defined
Stacktrace:
 [1] top-level scope at none:0

Adding `using Mimi` and `using VegaLite` did solve the problem.

**Comment by lrennels** [comment]
I have added a new issue for Tutorial 2 #396, we will either decide to release DICE2010 or base that tutorial on a different model.
