### ISSUE TITLE
Expand the API documentation

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/Mimi.jl#4]
Right now the doc strings in the source code file are very brief, they should minimally explain what the parameters do etc.

**Comment by lrennels** [comment]
- I noticed that right now there are links on the Repo homepage to various versions of documentation including  `stable` and `latest`.  The version labeled `stable` is what is accessed when a user follows the `Documentation` link … but it seems to be quite old.  Can we change this somehow?  
- Older versions of `make.jl` use `MkDocs` to help link up `references.md` with in-line function descriptions … but it seems we no longer use that package or automatic functionality, correct?
