### ISSUE TITLE
Scale y axis in explorer based on time window that is selected

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/Mimi.jl#402]
For example, here:

![image](https://user-images.githubusercontent.com/1036561/52985088-0c464e80-33a7-11e9-8961-be7f9f3ad9c3.png)

it would be nice if the y axis in the top plot had a smaller range so that one can make sense of the lines :)

This might be slightly tricky, because I guess one needs to adjust the scale somehow based on the selection, right?

**Comment by lrennels** [comment]
Good idea, I'm surprised that this isn't done in the examples.  The x axis domain scale is pulled from the brush selection, but simply doing the same with they y axis isn't effective, perhaps because the brush selection is only done on the x encoding.  I'll look into it.
