### ISSUE TITLE
Plotting

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/Mimi.jl#47]
The simplest interface would be if

``` julia
plot(m, :componentname, :variablename)
```

would work. Another option would be that `m[:componentname, :varname]` returned a custom type, and then we might be able to use https://github.com/JuliaPlots/PlotRecipes.jl somehow to hook into the Plots.jl framework.

As a first step we should implement the first option in this issue here.

**Comment by swerwath** [comment]
@davidanthoff could you assign this to me when you get a chance?
