### ISSUE TITLE
Test arguments

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/Mimi.jl#58]
Generally we need to make sure that we validate the input arguments for each public API method before we start the actual work.

**Comment by davidanthoff** [comment]
List of functions:
- [ ] ``run``: check that model has >0 components, check that there are no unset parameters, check that time index is set.
- [ ] ``addcomponent``: check ``t``, check whether component with same name exists already, check whether ``before`` and ``after`` components actually exist.
- [ ] ``setparameter``: Lots
- [ ] ``connectparameter``: Lots
- [ ] ``getindex``, check whether component/var combo exists
- [ ] ``getdataframe`` same
- [ ] ``addparameter``, check for duplicates
- [ ] ``plot`` Check for existence of compos/vars, but might be covered by previous checks.

**Comment by girishbalaji** [comment]
I'm slightly confused as to what checks to add for setparameter and the add and connect parameters. I'm not sure what would be different between the three as well
