### ISSUE TITLE
Drop julia 0.4 support

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/Mimi.jl#60]
This is mainly a question for @jrising: when can we drop julia 0.4 support? All my models are ready. When we drop support for old versions, we would only drop it for newer Mimi versions, all the existing tagged versions would still work on julia 0.4

**Comment by jrising** [comment]
I can't switch to 0.5 yet-- I would risk losing people.  But we can stick to a tagged version of Mimi.

**Comment by davidanthoff** [comment]
Alright, then I'll drop julia 0.5 support on master and going forward.
