### ISSUE TITLE
Try to remove lintr code from being accounted for in code coverage 

### ISSUE THREAD

**Issue by girishbalaji** [anthofflab/Mimi.jl#71]

**Comment by davidanthoff** [comment]
Research https://github.com/JuliaCI/Coverage.jl

**Comment by girishbalaji** [comment]
I looked into the package and found this pull request that was last updated in August.
https://github.com/JuliaCI/Coverage.jl/pull/55
I don't think these commits have been merged and am not sure if there's better way to go around it

**Comment by davidanthoff** [comment]
Yeah, I think that just means we can't do it right now. I'll add another label for these situations, i.e. things we want to do but can't because we are blocked by upstream problems. Thanks for investigating!
