### ISSUE TITLE
setparameter has a bug when multiple components have a parameter with the same name

### ISSUE THREAD

**Issue by davidanthoff** [anthofflab/Mimi.jl#8]
Calling `setparameter` will override a potential other parameter of a different component with the same name, which is a bug.

**Comment by jrising** [comment]
I have run into this many times, and to my mind it should be solved by redefining `external_parameters` to be component-specific.  That is:
```
external_parameters::Dict{Symbol, Dict{Symbol, Parameter}}
```
where the first level is the component name, followed by parameter name.  It requires changes to a few functions (but not many), and could be phased in by having this structure live alongsde the current `external_parameters` (call it `component_parameters`?), and `connectparameter` sets the parameter in both.
