### ISSUE TITLE
Access parameter values the same way as variables.

### ISSUE THREAD

**Issue by FrankErrickson** [anthofflab/Mimi.jl#84]
It would be great if you could access the parameter values used to run a model the same way you can access variables.  For instance with a climate model `m`:

To access the calculated values of the variable `temperature` in a specific component you write:
`m[:climate_component, :temperature]`.

If I wanted to access the supplied value for the parameter `climate_sensitivity` used to run that specific component, it would be nice to just say: `m[:temp_component, :climate_sensitivity]`.  

I could also see a benefit to having slightly different syntax from the variable case just to keep it clear what the model is actually calculating, like:
`getparam(m, :temp_component, :climate_sensitivity)` or with a parameter indicator
`m[:temp_component, :parameter, :climate_sensitivity]`.

**Comment by ckingdon95** [comment]
PR #93
